spring.application.name=sms-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/sms
spring.datasource.username=chenshuzhu

spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}
